version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: ./dev-Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    command: './sbt run'

#sbt universal:packageBin

